name: LaTeX Compile and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Compile LaTeX Document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: card.tex  # Change this to your LaTeX file name

    - name: Upload PDF as Release Asset
      uses: actions/upload-artifact@v3
      with:
        name: PDF
        path: card.pdf  # Change this to your LaTeX output file name
