name: LaTeX Compile and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # - name: Install XeTeX
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install texlive-xetex -y

    - name: Compile LaTeX Document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: card.tex  # Change this to your LaTeX file name
        latexmk_use_xelatex: true

    - name: Upload PDF as Release Asset
      uses: actions/upload-artifact@v3
      with:
        name: PDF
        path: card.pdf  # Change this to your LaTeX output file name

    - name:  Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: card.pdf
        token: ${{ secrets.GITHUB_TOKEN }}
